# Generated by Django 6.1.1 on 2026-09-15 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tareas',
            new_name='Tarea',
        ),
    ]
